#!/bin/bash

#
# shellbatch will prepare and submit a bash script job to the SLURM queue on the DCC cluster by SLURM script

# Test usage; if incorrect, output correct usage
if [ "$#" -gt 2  -o  "$#" -eq 0 ]; then
	echo "********************************************************************"
	echo "*                        Matbatch version 0.1                      *"
	echo "********************************************************************"
	echo "The 'matbatch' script submits Matlab batch jobs to the DCSR cluster using SLURM."
	echo ""
	echo "Usage is:"
	echo "         matbatch <input_file.m> [<output_file.log>]"
	echo ""
	echo "If only input_file.m is provided, then input_file.log will be created."
	echo ""
	echo "Spaces in the filename or directory name may cause failure."
	echo ""
else
	# Stem and extension of file
	filestem=`echo $1 | cut -f1 -d.`
	extension=`echo $1 | cut -f2 -d.`
	
	# Test if file exist
	if [ ! -r $1 ]; then
		echo ""
		echo "File does not exist"
		echo ""
	else
		# Direct output, conditional on number of arguments
		if [ "$#" -eq 1 ]; then
			output=$filestem.log
		else
			output=$2
		fi
		
		# Use user-defined 'TMPDIR' if possible; else, use /work/tmr17
		if [[ -n $TMPDIR ]]; then
			pathy=$TMPDIR
		else
			pathy=/work/tmr17
		fi
		
		# Tempfile for the script
		shell=`mktemp $pathy/shell.XXXXXX` || exit 1
		chmod 700 $shell
		
		# Create script
		echo "#!/bin/tcsh"                        >> $shell
		
		# SLURM metacommands
		echo "#SBATCH --job-name=matbatch"        >> $shell
		echo "#SBATCH --output=$output"           >> $shell
		echo "#SBATCH --mail-type=END"            >> $shell
		echo "#SBATCH --mail-user=email@address.com" >> $shell
		# echo "#SBATCH --time=1:00:00:00"          >> $shell
		echo "#SBATCH --mem=30G"                  >> $shell
        echo "#SBATCH --partition=econ,scavenger" >> $shell
        # echo "#SBATCH -w dcc-econ-20"            >> $shell
		echo "bash $filestem" >> $shell
		sbatch $shell
	fi
fi


