#!/bin/bash

#
# Statabatch will prepare and submit a Stata-SE job to the SLURM queue on the DCSR cluster by SLURM script

# PATH=$PATH:/usr/local/gauss:/usr/local/stata

# Test usage; if incorrect, output correct usage
if [ "$#" -gt 2  -o  "$#" -eq 0 ]; then
	echo "********************************************************************"
	echo "*                        Statabatch version 0.1                    *"
	echo "********************************************************************"
	echo "The 'statabatch' script submits Stata-SE batch jobs to the DCSR cluster using SLURM."
	echo ""
	echo "Usage is:"
	echo "         statabatch <input_file.do> [<output_file.log>]"
	echo ""
	echo "If only input_file.do is provided, then input_file.log will be created."
	echo ""
	echo "Spaces in the filename or directory name may cause failure."
	echo ""
else
	# Stem and extension of file
	filestem=`echo $1 | cut -f1 -d.`
	extension=`echo $1 | cut -f2 -d.`
	
	# Test if file exist
	if [ ! -r $1 ]; then
		echo ""
		echo "File does not exist"
		echo ""
	elif [ $extension != do ]; then
		echo ""
		echo "Invalid input file, must be a do-file"
		echo ""
	else
		# Direct output, conditional on number of arguments
		if [ "$#" -eq 1 ]; then
			output=$filestem.log
		else
			output=$2
		fi
		
		# Use user-defined 'TMPDIR' if possible; else, use /work/tmr17
		if [[ -n $TMPDIR ]]; then
			pathy=$TMPDIR
		else
			pathy=/work/tmr17
		fi
		
		# Tempfile for the script
		shell=`mktemp $pathy/shell.XXXXXX` || exit 1
		chmod 700 $shell
		
		# Create script
		echo "#!/bin/tcsh"                        >> $shell
		
		# SLURM metacommands
		echo "#SBATCH --job-name=statabatch"      >> $shell
		echo "#SBATCH --output=$output"           >> $shell
		echo "#SBATCH --mail-type=END"            >> $shell
		echo "#SBATCH --mail-user=email@address.com" >> $shell
		# echo "#SBATCH --time=1:00:00:00"          >> $shell
		echo "#SBATCH --mem=10G"                  >> $shell
        echo "#SBATCH --partition=econ"           >> $shell
        # echo "#SBATCH -w dcc-econ-20"             >> $shell
		echo "stata-se -b do $filestem" >> $shell
		sbatch $shell
	fi
fi
