function Utils = createfutureflowsconsumpstruct(data,priorabilstruct,consumps,Beta,S,num_GPA_pctiles,q,AdjNG,AdjG,CRRA);

    v2struct(data);
    v2struct(priorabilstruct);
    v2struct(consumps);

    if CRRA<=0.2
        multiplier = 1/10000;
    elseif CRRA>0.2 & CRRA<=0.4
        multiplier = 1/1000;
    elseif CRRA>0.4 & CRRA<=0.7
        multiplier = 1/100;
    elseif CRRA>0.7 & CRRA<1.0
        multiplier = 1/10;
    elseif CRRA>1.0 & CRRA<=1.2
        multiplier = 1;
    elseif CRRA>1.2 & CRRA<=1.4
        multiplier = 10;
    elseif CRRA>1.4 & CRRA<=1.5
        multiplier = 100;
    elseif CRRA>1.6 & CRRA<=1.8
        multiplier = 1000;
    elseif CRRA>1.8 & CRRA<=2.0
        multiplier = 10000;
    end

    %% Form current and future flow utilities for structural MLE
    % u_{j,t} (X components)
    demog=[ones(N*T,1) black hispanic HS_grades Parent_college birthYr==1980 birthYr==1981 birthYr==1982 birthYr==1983 famInc];
    sdemog = size(demog,2);
    [~,demogs]               = makegrid(demog,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    demogs                   = demogs(:,1:end-(S-1));
    [~,sexper]               = makegrid(exper,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sexper_postgrad]      = makegrid(exper_postgrad,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sprev_HS]             = makegrid(prev_HS,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sprev_2yr]            = makegrid(prev_2yr,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sprev_4yrS]           = makegridchoice(prev_4yrS,asifsci.prev_4yrS,asifhum.prev_4yrS,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sprev_4yrNS]          = makegridchoice(prev_4yrNS,asifsci.prev_4yrNS,asifhum.prev_4yrNS,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sprev_PT]             = makegrid(prev_PT,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sprev_FT]             = makegrid(prev_FT,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sprev_WC]             = makegrid(prev_WC,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sage]                 = makegrid(age,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,smale]                = makegrid(male,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sgrad_4yr]            = makegrid(grad_4yr,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
           A                 = [1 1 1; 1 1 0; 1 0 1; 1 0 0; 0 1 1; 0 1 0; 0 0 1; 0 0 0];
       stype                 = kron(A,ones(Ntilde*T,1));
    [~,scum_2yr]             = makegrid(cum_2yr,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,scum_4yr]             = makegrid(cum_4yr,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    [~,sfinsci]              = makegrid(finalMajorSci,impMajlp,impGPAlp,impMajGPAlp,num_GPA_pctiles,S);
    scum_school              = scum_2yr+scum_4yr;
    obs_abil_vec             = zeros(size(prior_ability_4S_vec));
    obs_abil_vec(sfinsci==1) = prior_ability_4S_vec(sfinsci==1);
    obs_abil_vec(sfinsci==0) = prior_ability_4NS_vec(sfinsci==0);
    sprevs                   = [sprev_HS sprev_2yr sprev_4yrS sprev_4yrNS sprev_PT sprev_FT sprev_WC];

    %Non-grad flow utilities (last 6 before types are: grad_4yr, workWC, workPT, workFT, workPT*white_collar, workFT*white_collar)
    X2ftbc   = [(1-Beta).*[demogs prior_ability_2_vec  ] multiplier.*([consump(:,1 )-Beta.*consump_t1(:,1 )]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) stype]];
    X2ftwc   = [(1-Beta).*[demogs prior_ability_2_vec  ] multiplier.*([consump(:,2 )-Beta.*consump_t1(:,2 )]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) stype]];
    X2ptbc   = [(1-Beta).*[demogs prior_ability_2_vec  ] multiplier.*([consump(:,3 )-Beta.*consump_t1(:,3 )]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) stype]];
    X2ptwc   = [(1-Beta).*[demogs prior_ability_2_vec  ] multiplier.*([consump(:,4 )-Beta.*consump_t1(:,4 )]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) stype]];
    X2nw     = [(1-Beta).*[demogs prior_ability_2_vec  ] multiplier.*([consump(:,5 )-Beta.*consump_t1(:,5 )]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[                    zeros(Ntilde*T*S,6)                     stype]];
    X4sftbc  = [(1-Beta).*[demogs prior_ability_4S_vec ] multiplier.*([consump(:,6 )-Beta.*consump_t1(:,6 )]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) stype]];
    X4sftwc  = [(1-Beta).*[demogs prior_ability_4S_vec ] multiplier.*([consump(:,7 )-Beta.*consump_t1(:,7 )]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) stype]];
    X4sptbc  = [(1-Beta).*[demogs prior_ability_4S_vec ] multiplier.*([consump(:,8 )-Beta.*consump_t1(:,8 )]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) stype]];
    X4sptwc  = [(1-Beta).*[demogs prior_ability_4S_vec ] multiplier.*([consump(:,9 )-Beta.*consump_t1(:,9 )]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) stype]];
    X4snw    = [(1-Beta).*[demogs prior_ability_4S_vec ] multiplier.*([consump(:,10)-Beta.*consump_t1(:,10)]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[                    zeros(Ntilde*T*S,6)                     stype]];
    X4nsftbc = [(1-Beta).*[demogs prior_ability_4NS_vec] multiplier.*([consump(:,11)-Beta.*consump_t1(:,11)]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) stype]];
    X4nsftwc = [(1-Beta).*[demogs prior_ability_4NS_vec] multiplier.*([consump(:,12)-Beta.*consump_t1(:,12)]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) stype]];
    X4nsptbc = [(1-Beta).*[demogs prior_ability_4NS_vec] multiplier.*([consump(:,13)-Beta.*consump_t1(:,13)]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) stype]];
    X4nsptwc = [(1-Beta).*[demogs prior_ability_4NS_vec] multiplier.*([consump(:,14)-Beta.*consump_t1(:,14)]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) stype]];
    X4nsnw   = [(1-Beta).*[demogs prior_ability_4NS_vec] multiplier.*([consump(:,15)-Beta.*consump_t1(:,15)]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[                    zeros(Ntilde*T*S,6)                     stype]];
    Xngwptbc = [(1-Beta).*[demogs zeros(Ntilde*T*S,1)  ] multiplier.*([consump(:,16)-Beta.*consump_t1(:,16)]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,4) stype]];
    Xngwptwc = [(1-Beta).*[demogs zeros(Ntilde*T*S,1)  ] multiplier.*([consump(:,17)-Beta.*consump_t1(:,17)]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,4) stype]];
    Xngwftbc = [(1-Beta).*[demogs zeros(Ntilde*T*S,1)  ] multiplier.*([consump(:,18)-Beta.*consump_t1(:,18)]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,4) stype]];
    Xngwftwc = [(1-Beta).*[demogs zeros(Ntilde*T*S,1)  ] multiplier.*([consump(:,19)-Beta.*consump_t1(:,19)]-[consump(:,20)-Beta.*consump_t1(:,20)]) sprevs (1-Beta).*[zeros(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,4) stype]];

    % Grad flow utilities
    Xgwptbc  = [(1-Beta).*[demogs zeros(Ntilde*T*S,1)  ] multiplier.*([consump_g(:,16)-Beta.*consump_g_t1(:,16)]-[consump_g(:,20)-Beta.*consump_g_t1(:,20)]) sprevs (1-Beta).*[ ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,4)                     stype]];
    Xgwptwc  = [(1-Beta).*[demogs zeros(Ntilde*T*S,1)  ] multiplier.*([consump_g(:,17)-Beta.*consump_g_t1(:,17)]-[consump_g(:,20)-Beta.*consump_g_t1(:,20)]) sprevs (1-Beta).*[ ones(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,4)                     stype]];
    Xgwftbc  = [(1-Beta).*[demogs zeros(Ntilde*T*S,1)  ] multiplier.*([consump_g(:,18)-Beta.*consump_g_t1(:,18)]-[consump_g(:,20)-Beta.*consump_g_t1(:,20)]) sprevs (1-Beta).*[ ones(Ntilde*T*S,1) zeros(Ntilde*T*S,1) zeros(Ntilde*T*S,4)                     stype]];
    Xgwftwc  = [(1-Beta).*[demogs zeros(Ntilde*T*S,1)  ] multiplier.*([consump_g(:,19)-Beta.*consump_g_t1(:,19)]-[consump_g(:,20)-Beta.*consump_g_t1(:,20)]) sprevs (1-Beta).*[ ones(Ntilde*T*S,1)  ones(Ntilde*T*S,1) zeros(Ntilde*T*S,4)                     stype]];

    % create variable to indicate time period
    Ymat        = reshape(ClImps,[T Ntilde*S])';
    permat      = (Ymat>0).*cumsum(Ymat>0,2);
    periodlImps = reshape(permute(permat,[2 1]),[],1);

    % summary stats of consumption terms
    disp('all periods');
    % non-grads
    fff = (ClImps>0 & grad_4yrlImps==0);
    sumopt = struct('Weights',q(fff));
    summat = cat(2,multiplier.*[consump(fff,1 )-Beta.*consump_t1(fff,1 )],...
                   multiplier.*[consump(fff,2 )-Beta.*consump_t1(fff,2 )],...
                   multiplier.*[consump(fff,3 )-Beta.*consump_t1(fff,3 )],...
                   multiplier.*[consump(fff,4 )-Beta.*consump_t1(fff,4 )],...
                   multiplier.*[consump(fff,5 )-Beta.*consump_t1(fff,5 )],...
                   multiplier.*[consump(fff,6 )-Beta.*consump_t1(fff,6 )],...
                   multiplier.*[consump(fff,7 )-Beta.*consump_t1(fff,7 )],...
                   multiplier.*[consump(fff,8 )-Beta.*consump_t1(fff,8 )],...
                   multiplier.*[consump(fff,9 )-Beta.*consump_t1(fff,9 )],...
                   multiplier.*[consump(fff,10)-Beta.*consump_t1(fff,10)],...
                   multiplier.*[consump(fff,11)-Beta.*consump_t1(fff,11)],...
                   multiplier.*[consump(fff,12)-Beta.*consump_t1(fff,12)],...
                   multiplier.*[consump(fff,13)-Beta.*consump_t1(fff,13)],...
                   multiplier.*[consump(fff,14)-Beta.*consump_t1(fff,14)],...
                   multiplier.*[consump(fff,15)-Beta.*consump_t1(fff,15)],...
                   multiplier.*[consump(fff,16)-Beta.*consump_t1(fff,16)],...
                   multiplier.*[consump(fff,17)-Beta.*consump_t1(fff,17)],...
                   multiplier.*[consump(fff,18)-Beta.*consump_t1(fff,18)],...
                   multiplier.*[consump(fff,19)-Beta.*consump_t1(fff,19)],...
                   multiplier.*[consump(fff,20)-Beta.*consump_t1(fff,20)]);
    summarize(summat,sumopt);
    % grads
    fff = (ClImps>0 & grad_4yrlImps==1);
    sumopt = struct('Weights',q(fff));
    summat = cat(2,multiplier.*[consump_g(fff,16)-Beta.*consump_g_t1(fff,16)],...
                   multiplier.*[consump_g(fff,17)-Beta.*consump_g_t1(fff,17)],...
                   multiplier.*[consump_g(fff,18)-Beta.*consump_g_t1(fff,18)],...
                   multiplier.*[consump_g(fff,19)-Beta.*consump_g_t1(fff,19)],...
                   multiplier.*[consump_g(fff,20)-Beta.*consump_g_t1(fff,20)]);
    summarize(summat,sumopt);

    % summary stats of consumption terms
    disp('period 1');
    % non-grads
    fff = (ClImps>0 & grad_4yrlImps==0 & periodlImps==1);
    sumopt = struct('Weights',q(fff));
    summat = cat(2,multiplier.*[consump(fff,1 )-Beta.*consump_t1(fff,1 )],...
                   multiplier.*[consump(fff,2 )-Beta.*consump_t1(fff,2 )],...
                   multiplier.*[consump(fff,3 )-Beta.*consump_t1(fff,3 )],...
                   multiplier.*[consump(fff,4 )-Beta.*consump_t1(fff,4 )],...
                   multiplier.*[consump(fff,5 )-Beta.*consump_t1(fff,5 )],...
                   multiplier.*[consump(fff,6 )-Beta.*consump_t1(fff,6 )],...
                   multiplier.*[consump(fff,7 )-Beta.*consump_t1(fff,7 )],...
                   multiplier.*[consump(fff,8 )-Beta.*consump_t1(fff,8 )],...
                   multiplier.*[consump(fff,9 )-Beta.*consump_t1(fff,9 )],...
                   multiplier.*[consump(fff,10)-Beta.*consump_t1(fff,10)],...
                   multiplier.*[consump(fff,11)-Beta.*consump_t1(fff,11)],...
                   multiplier.*[consump(fff,12)-Beta.*consump_t1(fff,12)],...
                   multiplier.*[consump(fff,13)-Beta.*consump_t1(fff,13)],...
                   multiplier.*[consump(fff,14)-Beta.*consump_t1(fff,14)],...
                   multiplier.*[consump(fff,15)-Beta.*consump_t1(fff,15)],...
                   multiplier.*[consump(fff,16)-Beta.*consump_t1(fff,16)],...
                   multiplier.*[consump(fff,17)-Beta.*consump_t1(fff,17)],...
                   multiplier.*[consump(fff,18)-Beta.*consump_t1(fff,18)],...
                   multiplier.*[consump(fff,19)-Beta.*consump_t1(fff,19)],...
                   multiplier.*[consump(fff,20)-Beta.*consump_t1(fff,20)]);
    summarize(summat,sumopt);

    % summary stats of consumption terms
    disp('how often is work-in-school smaller than school only?');
    % non-grads
    fff = (ClImps>0 & grad_4yrlImps==0 & periodlImps==1);
    sumopt = struct('Weights',q(fff));
    summat = cat(2,multiplier.*[consump(fff,1 )-Beta.*consump_t1(fff,1 )]<multiplier.*[consump(fff,5 )-Beta.*consump_t1(fff,5 )],...
                   multiplier.*[consump(fff,2 )-Beta.*consump_t1(fff,2 )]<multiplier.*[consump(fff,5 )-Beta.*consump_t1(fff,5 )],...
                   multiplier.*[consump(fff,3 )-Beta.*consump_t1(fff,3 )]<multiplier.*[consump(fff,5 )-Beta.*consump_t1(fff,5 )],...
                   multiplier.*[consump(fff,4 )-Beta.*consump_t1(fff,4 )]<multiplier.*[consump(fff,5 )-Beta.*consump_t1(fff,5 )],...
                   multiplier.*[consump(fff,5 )-Beta.*consump_t1(fff,5 )]<multiplier.*[consump(fff,5 )-Beta.*consump_t1(fff,5 )],...
                   multiplier.*[consump(fff,6 )-Beta.*consump_t1(fff,6 )]<multiplier.*[consump(fff,10)-Beta.*consump_t1(fff,10)],...
                   multiplier.*[consump(fff,7 )-Beta.*consump_t1(fff,7 )]<multiplier.*[consump(fff,10)-Beta.*consump_t1(fff,10)],...
                   multiplier.*[consump(fff,8 )-Beta.*consump_t1(fff,8 )]<multiplier.*[consump(fff,10)-Beta.*consump_t1(fff,10)],...
                   multiplier.*[consump(fff,9 )-Beta.*consump_t1(fff,9 )]<multiplier.*[consump(fff,10)-Beta.*consump_t1(fff,10)],...
                   multiplier.*[consump(fff,10)-Beta.*consump_t1(fff,10)]<multiplier.*[consump(fff,10)-Beta.*consump_t1(fff,10)],...
                   multiplier.*[consump(fff,11)-Beta.*consump_t1(fff,11)]<multiplier.*[consump(fff,15)-Beta.*consump_t1(fff,15)],...
                   multiplier.*[consump(fff,12)-Beta.*consump_t1(fff,12)]<multiplier.*[consump(fff,15)-Beta.*consump_t1(fff,15)],...
                   multiplier.*[consump(fff,13)-Beta.*consump_t1(fff,13)]<multiplier.*[consump(fff,15)-Beta.*consump_t1(fff,15)],...
                   multiplier.*[consump(fff,14)-Beta.*consump_t1(fff,14)]<multiplier.*[consump(fff,15)-Beta.*consump_t1(fff,15)],...
                   multiplier.*[consump(fff,15)-Beta.*consump_t1(fff,15)]<multiplier.*[consump(fff,15)-Beta.*consump_t1(fff,15)]);
    summarize(summat,sumopt);

    % summary stats of adjustment terms
    disp('all periods');
    % non-grads
    fff = (ClImps>0 & grad_4yrlImps==0);
    sumopt = struct('Weights',q(fff));
    summat = cat(2,AdjNG(fff,1 ),...
                   AdjNG(fff,2 ),...
                   AdjNG(fff,3 ),...
                   AdjNG(fff,4 ),...
                   AdjNG(fff,5 ),...
                   AdjNG(fff,6 ),...
                   AdjNG(fff,7 ),...
                   AdjNG(fff,8 ),...
                   AdjNG(fff,9 ),...
                   AdjNG(fff,10),...
                   AdjNG(fff,11),...
                   AdjNG(fff,12),...
                   AdjNG(fff,13),...
                   AdjNG(fff,14),...
                   AdjNG(fff,15),...
                   AdjNG(fff,16),...
                   AdjNG(fff,17),...
                   AdjNG(fff,18),...
                   AdjNG(fff,19),...
                   AdjNG(fff,20));
    summarize(summat,sumopt);
    % grads
    fff = (ClImps>0 & grad_4yrlImps==1);
    sumopt = struct('Weights',q(fff));
    summat = cat(2,AdjG(fff,16),...
                   AdjG(fff,17),...
                   AdjG(fff,18),...
                   AdjG(fff,19),...
                   AdjG(fff,20));
    summarize(summat,sumopt);

    % summary stats of consumption terms
    disp('period 1');
    % non-grads
    fff = (ClImps>0 & grad_4yrlImps==0 & periodlImps==1);
    sumopt = struct('Weights',q(fff));
    summat = cat(2,AdjNG(fff,1 ),...
                   AdjNG(fff,2 ),...
                   AdjNG(fff,3 ),...
                   AdjNG(fff,4 ),...
                   AdjNG(fff,5 ),...
                   AdjNG(fff,6 ),...
                   AdjNG(fff,7 ),...
                   AdjNG(fff,8 ),...
                   AdjNG(fff,9 ),...
                   AdjNG(fff,10),...
                   AdjNG(fff,11),...
                   AdjNG(fff,12),...
                   AdjNG(fff,13),...
                   AdjNG(fff,14),...
                   AdjNG(fff,15),...
                   AdjNG(fff,16),...
                   AdjNG(fff,17),...
                   AdjNG(fff,18),...
                   AdjNG(fff,19),...
                   AdjNG(fff,20));
    summarize(summat,sumopt);

    Utils = v2struct(sdemog,X2ftbc,X2ftwc,X2ptbc,X2ptwc,X2nw,X4sftbc,X4sftwc,X4sptbc,X4sptwc,X4snw,X4nsftbc,X4nsftwc,X4nsptbc,X4nsptwc,X4nsnw,Xngwptbc,Xngwptwc,Xngwftbc,Xngwftwc,Xgwptbc,Xgwptwc,Xgwftbc,Xgwftwc,stype,sprevs,sage,ClImps,grad_4yrlImps);
end
